"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2--bt()w7e4@@tcxph+9@sg1d^j*ef5#t2ys%3*6b1*6#3%z$9"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "accounts",
    "projects",
    "skills",  # required by allauth
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    # Authentication
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",  # Add other providers as needed
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "debug_toolbar",
    "django_filters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    # "django_brotli.middleware.BrotliMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "portfolio_db",
#         "USER": "dubsy",
#         "PASSWORD": "password",
#         "HOST": "localhost",  # Works for both Docker and Native
#         "PORT": "5432",
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
AUTH_USER_MODEL = "accounts.User"
SITE_ID = 1

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.VersionedJWTAuthentication",
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "access",
    "JWT_AUTH_REFRESH_COOKIE": "refresh",
    "JWT_AUTH_HTTPONLY": False,  # Set to True in production for security
    "JWT_AUTH_RETURN_EXPIRATION": True,  # Include token expiration in response
    "SESSION_LOGIN": False,  # Disable session-based login (pure token auth)
    "USER_DETAILS_SERIALIZER": "accounts.serializers.AuthUserSerializer",  # Return user data on login
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=60),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": settings.SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "TOKEN_OBTAIN_SERIALIZER": "accounts.serializers.CustomTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
    "CHECK_REVOKE_TOKEN": False,
    "REVOKE_TOKEN_CLAIM": "hash_password",
    "CHECK_USER_IS_ACTIVE": True,
}

ACCOUNT_LOGIN_METHODS = {"email"}  # replaces ACCOUNT_AUTHENTICATION_METHOD
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]  #
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # User CANNOT login until they click the link
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # Verify directly when link is clicked
ACCOUNT_USER_MODEL_USERNAME_FIELD = None


# 6. Email Backend (CRITICAL FOR DEV)
# Since you are on PC, this prints the email to your Terminal instead of sending it.
# Switch to SMTP (Gmail/SendGrid) for production.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# settings.py
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "github": {
        "SCOPE": ["read:user", "user:email"],
    },
}

# =============================================================================
# OAUTH CREDENTIALS
# =============================================================================
# These should be moved to environment variables in production!
# For Google: https://console.cloud.google.com/apis/credentials
# For GitHub: https://github.com/settings/developers

GOOGLE_CLIENT_ID = (
    "452791306166-h0ngbkmjhkk77e3hlmdpbdjbgp1pgp4q.apps.googleusercontent.com"
)
GOOGLE_CLIENT_SECRET = ""  # Add your Google client secret here

GITHUB_CLIENT_ID = "Ov23li3qhgSGte2FwEYb"  # Add your GitHub client ID
GITHUB_CLIENT_SECRET = ""  # Add your GitHub client secret

# Callback URLs - These should match what's registered in OAuth provider consoles
# For development, these point to your BACKEND callback endpoints
# The backend will redirect to your frontend with the code
GOOGLE_CALLBACK_URL = "http://localhost:8000/api/v1/auth/social/google/callback/"
GITHUB_CALLBACK_URL = "http://localhost:8000/api/v1/auth/social/github/callback/"

# Frontend URL - Where users are redirected after OAuth callback
# FRONTEND_URL = "http://localhost:3000"

# =============================================================================
# SOCIAL ACCOUNT SETTINGS
# =============================================================================
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # Allow login via email from social
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = (
    True  # Auto-link social to existing email
)
SOCIALACCOUNT_EMAIL_REQUIRED = True  # Require email from social providers
SOCIALACCOUNT_QUERY_EMAIL = True  # Query email from provider if not provided
SOCIALACCOUNT_STORE_TOKENS = True  # Store provider tokens for API calls if needed

# =============================================================================
# CUSTOM ADAPTERS - Ensures username = email for social auth users
# =============================================================================
ACCOUNT_ADAPTER = "accounts.adapters.CustomAccountAdapter"
SOCIALACCOUNT_ADAPTER = "accounts.adapters.CustomSocialAccountAdapter"


CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Optional: Task execution settings
CELERY_TASK_ACKS_LATE = True  # Acknowledge after task completes
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Re-queue if worker dies
CELERY_TASK_TIME_LIMIT = 300  # 5 minute timeout


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # Use different DB than Celery
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "KEY_PREFIX": "portfolio",  # Prefix all keys to avoid collisions
        "TIMEOUT": 300,  # Default timeout: 5 minutes
    }
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Developer Portfolio API",
    "DESCRIPTION": """
## Overview
A robust Django REST Framework backend designed to power a Developer Portfolio application.
This system manages user authentication, project showcases, and technical skill tracking
with a focus on security and data integrity.

## Features
- **JWT Authentication** - Secure token-based auth with HTTP-only cookie support
- **Social OAuth** - Login via Google and GitHub
- **Project Management** - Full CRUD operations for portfolio projects with tech stack tracking
- **Skills Tracking** - Categorized technical skills management
- **Email Verification** - Mandatory email verification for new accounts
- **Async Tasks** - Background email sending via Celery

## Authentication
Most endpoints require JWT authentication. Include the token in your requests:

```
Authorization: Bearer <access_token>
```

Or use the `access` cookie if JWT cookies are enabled.

## Token Lifecycle
- **Access Token**: Valid for 5 minutes
- **Refresh Token**: Valid for 60 minutes
- Tokens are rotated on refresh for enhanced security
    """,
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    # Split request body into separate components for clarity
    "COMPONENT_SPLIT_REQUEST": True,
    # Sort operations alphabetically within tags
    "SORT_OPERATIONS": True,
    # Define tag order and descriptions
    "TAGS": [
        {
            "name": "Authentication",
            "description": "User registration, login, logout, and email verification",
        },
        {
            "name": "Password Management",
            "description": "Password reset and change operations",
        },
        {
            "name": "User Profile",
            "description": "User profile retrieval and management",
        },
        {
            "name": "Social Authentication",
            "description": "OAuth login via Google and GitHub providers",
        },
        {
            "name": "Projects",
            "description": "Portfolio project management - create, read, update, delete projects",
        },
        {
            "name": "Skills",
            "description": "Technical skills and skill categories management",
        },
        {
            "name": "Skill Categories",
            "description": "Skill category organization (Frontend, Backend, DevOps, etc.)",
        },
    ],
    # External documentation link
    "EXTERNAL_DOCS": {
        "description": "GitHub Repository",
        "url": "https://github.com/BackendPhantom/portfolio_api",
    },
    # Contact information
    "CONTACT": {
        "name": "API Support",
        "url": "https://github.com/BackendPhantom/portfolio_api/issues",
    },
    # License information
    "LICENSE": {
        "name": "MIT License",
        "url": "https://opensource.org/licenses/MIT",
    },
    # Swagger UI settings
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": False,
        "filter": True,
    },
    # Security schemes
    "SECURITY": [{"Bearer": []}],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "Bearer": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "JWT access token obtained from /api/v1/auth/login/",
            },
            "Cookie": {
                "type": "apiKey",
                "in": "cookie",
                "name": "access",
                "description": "JWT access token stored in HTTP-only cookie",
            },
        }
    },
}

# LOGGING = {
#     'version': 1,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'level': 'DEBUG',
#             'handlers': ['console'],
#         },
#     },
# }


# Time a login request
