# Generated by Django 5.2.11 on 2026-03-03 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(editable=False, max_length=255, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("soft", "Soft Skill"),
                            ("technical", "Technical Skill"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=True,
                        help_text="System categories cannot be modified or deleted.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Skill Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SkillSubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"category_type": "technical"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="skills.skillcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_subcategories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Subcategory",
                "verbose_name_plural": "Skill Subcategories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="technical",
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="skills.skillcategory",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skills",
                        to="skills.skillsubcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="skillsubcategory",
            index=models.Index(
                fields=["user", "name"], name="skills_skil_user_id_81291e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillsubcategory",
            index=models.Index(
                fields=["user", "category"], name="skills_skil_user_id_657ff1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillsubcategory",
            unique_together={("user", "name", "category")},
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["user", "category"], name="skills_skil_user_id_8b97f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["user", "name"], name="skills_skil_user_id_c1981e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("user", "category", "name", "sub_category")},
        ),
    ]
